// https://www.mulagofoundation.org/our-portfolio

export const options = [
  'Chancen International',
  'Dost',
  'Educate Girls',
  'Food 4 Education',
  'Imagine Worldwide',
  'Lively Minds',
  'Luminos Fund',
  'Ubongo',
  'Aceli Africa',
  'Babban Gona',
  'Digital Green',
  'Farmerline',
  'Hello Tractor',
  'Ignitia',
  'Kheyti',
  'Komaza',
  'Mountain Hazelnuts',
  'MyAgro',
  'One Acre Fund',
  'Precision Agriculture for Development',
  'Proximity Designs',
  'Pula',
  'West African Rice Company',
  'BOMA Project',
  'Bridges to Prosperity',
  'The/Nudge',
  'VisionSpring',
  'Amani Global Works',
  'Development Media International',
  'Equalize Health',
  'Friendship Bench',
  'Healthy Learners',
  'Integrate Health',
  'Intelehealth',
  'Last Mile Health',
  'Living Goods',
  'Lwala',
  'Medic',
  'Muso',
  'Nexleaf Analytics',
  'No Means No Worldwide',
  'Noora Health',
  'One Heart Worldwide',
  'PIVOT',
  'Sanku',
  'SaveLIFE Foundation',
  'Semilla Nueva',
  'StrongMinds',
  'THINKMD',
  'Turn',
  'VillageReach',
  'Young1ove',
  'mothers2mothers',
  'EarthEnable',
  'Saha Global',
  'Sanergy',
  'WSUP',
  'Blue Ventures',
  'COMACO',
  'Foundation for Ecological Security',
  'Gaia Amazonas',
  'Global Forest Watch',
  'Maliasili',
  'Nia Tero',
  'Zola Electric'
]
